name: Shell commands

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: Echo a string
          run: echo "Hello there!"
        - name: Commands in multiple lines
          run: |
            node -v
            npm -v
            echo "These are the versions..."