name: Shell commands

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: Echo a string
          run: echo "Hello there!"
        - name: Commands in multiple lines
          run: |
            node -v
            npm -v
            echo "These are the versions..."
        - name: python commands
          run: |
            import platform
            print(platform.processor())
          shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
        - name: Directory Powershell
          run: Get-Location
        - name: Directory Bash
          run: pwd
          shell: bash